version: "3"
services:
  db:
    image: postgres
    container_name: postgres-db
    volumes:
      - $PWD/db_data:/var/lib/postgresql/data 
      - $PWD/src/sql/directory.v1.sql:/sql/directory.v1.sql
    environment: 
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"
  redis_store:
    image: redis
    container_name: rdb
    volumes: 
      - $PWD/redis_data:/usr/local/etc/redis
    ports: 
      - "6379:6379"